eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8765
  tomcat:
    max-threads: 50
  
spring:
  application:
    name: diy-UserService
  devtools:
        restart:
        enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cltest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
        # hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启工程会删除表并新建
        show-sql: true
feign:
   hystrix:
     enabled: true
hystrix:
   command: 
     default: 
       execution: 
        isolation:
         thread: 
          timeoutInMilliseconds: 100000
 