eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8763
spring:
  application:
    name: diy-AnalysisService
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
  devtools:
    restart:
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aibshe?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    # hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启工程会删除表并新建
    show-sql: true


feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000


my_queue: springboot-queue
my_topic: springboot-topic